'use client'

import { useState, useRef } from 'react'
import type { Metadata } from 'next'
import { QRCodeSVG } from 'qrcode.react'
import { Download, Copy, Check, Link as LinkIcon, Wifi, Mail, Smartphone, HelpCircle } from 'lucide-react'

type QRType = 'text' | 'url' | 'email' | 'wifi' | 'phone'

interface PageProps {
    params: { locale: string }
}

export default function QRPage({ params }: PageProps) {
    const [qrType, setQRType] = useState<QRType>('text')
    const [value, setValue] = useState('https://orkiosk.com')
    const [size, setSize] = useState(256)
    const [errorLevel, setErrorLevel] = useState<'L' | 'M' | 'Q' | 'H'>('M')
    const [copied, setCopied] = useState(false)
    const [showTutorial, setShowTutorial] = useState(true)
    const qrRef = useRef<HTMLDivElement>(null)

    const isSpanish = params.locale === 'es'

    const copy = isSpanish ? {
        title: 'Generador de Códigos QR',
        subtitle: 'Crea códigos QR personalizados para cualquier propósito',
        typeLabel: 'Tipo de Contenido',
        types: {
            text: 'Texto',
            url: 'URL',
            email: 'Email',
            wifi: 'WiFi'
        },
        contentLabel: 'Contenido del QR',
        sizeLabel: 'Tamaño (px)',
        errorLabel: 'Corrección de Errores',
        previewTitle: 'Vista Previa',
        downloadButton: 'Descargar Código QR',
        tutorialTitle: '📚 Cómo Usar',
        tutorialSteps: [
            'Selecciona el tipo de contenido que deseas codificar',
            'Ingresa la información en el campo de texto',
            'Ajusta el tamaño y nivel de corrección según necesites',
            'Descarga el código QR como imagen PNG'
        ],
        infoTitle: '💡 Niveles de Corrección de Errores',
        infoText: 'Un nivel más alto permite que el QR sea escaneado incluso si está parcialmente dañado.',
        errorLevels: {
            L: { label: 'Bajo (7%)', desc: 'Más rápido de escanear' },
            M: { label: 'Medio (15%)', desc: 'Balance recomendado' },
            Q: { label: 'Alto (25%)', desc: 'Más robusto' },
            H: { label: 'Muy Alto (30%)', desc: 'Máxima corrección' }
        },
        footer: 'Generado por'
    } : {
        title: 'QR Code Generator',
        subtitle: 'Create custom QR codes for any purpose',
        typeLabel: 'Content Type',
        types: {
            text: 'Text',
            url: 'URL',
            email: 'Email',
            wifi: 'WiFi'
        },
        contentLabel: 'QR Content',
        sizeLabel: 'Size (px)',
        errorLabel: 'Error Correction',
        previewTitle: 'Preview',
        downloadButton: 'Download QR Code',
        tutorialTitle: '📚 How to Use',
        tutorialSteps: [
            'Select the type of content you want to encode',
            'Enter the information in the text field',
            'Adjust size and correction level as needed',
            'Download the QR code as PNG image'
        ],
        infoTitle: '💡 Error Correction Levels',
        infoText: 'A higher level allows the QR to be scanned even if partially damaged.',
        errorLevels: {
            L: { label: 'Low (7%)', desc: 'Faster to scan' },
            M: { label: 'Medium (15%)', desc: 'Recommended balance' },
            Q: { label: 'High (25%)', desc: 'More robust' },
            H: { label: 'Very High (30%)', desc: 'Maximum correction' }
        },
        footer: 'Generated by'
    }

    const qrTypes = [
        { id: 'text', icon: Smartphone },
        { id: 'url', icon: LinkIcon },
        { id: 'email', icon: Mail },
        { id: 'wifi', icon: Wifi }
    ]

    const downloadQR = () => {
        const svg = qrRef.current?.querySelector('svg')
        if (!svg) return

        const svgData = new XMLSerializer().serializeToString(svg)
        const canvas = document.createElement('canvas')
        const ctx = canvas.getContext('2d')
        const img = new Image()

        img.onload = () => {
            canvas.width = size
            canvas.height = size
            ctx?.drawImage(img, 0, 0)
            const pngFile = canvas.toDataURL('image/png')

            const downloadLink = document.createElement('a')
            downloadLink.download = `qr-code-${Date.now()}.png`
            downloadLink.href = pngFile
            downloadLink.click()
        }

        img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgData)))
    }

    const copyToClipboard = async () => {
        await navigator.clipboard.writeText(value)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    const getPlaceholder = () => {
        if (!isSpanish) {
            switch (qrType) {
                case 'url': return 'https://example.com'
                case 'email': return 'email@example.com'
                case 'wifi': return 'WIFI:T:WPA;S:NetworkName;P:Password;;'
                case 'phone': return '+1234567890'
                default: return 'Enter your text here...'
            }
        }
        switch (qrType) {
            case 'url': return 'https://ejemplo.com'
            case 'email': return 'correo@ejemplo.com'
            case 'wifi': return 'WIFI:T:WPA;S:NombreRed;P:Contraseña;;'
            case 'phone': return '+1234567890'
            default: return 'Ingresa tu texto aquí...'
        }
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 py-12 px-4">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="text-center mb-12">
                    <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                        {copy.title}
                    </h1>
                    <p className="text-gray-600 text-lg">
                        {copy.subtitle}
                    </p>
                </div>

                {/* Tutorial (Collapsible) */}
                {showTutorial && (
                    <div className="bg-purple-50 border-2 border-purple-200 rounded-2xl p-6 mb-8 relative">
                        <button
                            onClick={() => setShowTutorial(false)}
                            className="absolute top-4 right-4 text-purple-600 hover:text-purple-800"
                        >
                            ✕
                        </button>
                        <div className="flex items-start gap-3 mb-4">
                            <HelpCircle className="w-6 h-6 text-purple-600 flex-shrink-0 mt-1" />
                            <h3 className="text-xl font-bold text-purple-900">{copy.tutorialTitle}</h3>
                        </div>
                        <ol className="space-y-3 ml-2">
                            {copy.tutorialSteps.map((step, i) => (
                                <li key={i} className="flex gap-3">
                                    <span className="flex-shrink-0 w-6 h-6 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
                                        {i + 1}
                                    </span>
                                    <span className="text-purple-800 pt-0.5">{step}</span>
                                </li>
                            ))}
                        </ol>
                    </div>
                )}

                {/* Main Card */}
                <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12">
                    {/* Show Tutorial Button */}
                    {!showTutorial && (
                        <button
                            onClick={() => setShowTutorial(true)}
                            className="mb-6 flex items-center gap-2 text-purple-600 hover:text-purple-700 font-medium"
                        >
                            <HelpCircle className="w-5 h-5" />
                            {isSpanish ? 'Ver Tutorial' : 'Show Tutorial'}
                        </button>
                    )}

                    {/* QR Type Selector */}
                    <div className="mb-8">
                        <label className="block text-sm font-semibold text-gray-700 mb-3">
                            {copy.typeLabel}
                        </label>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                            {qrTypes.map(type => {
                                const Icon = type.icon
                                return (
                                    <button
                                        key={type.id}
                                        onClick={() => setQRType(type.id as QRType)}
                                        className={`p-4 rounded-xl border-2 transition-all flex flex-col items-center gap-2 ${qrType === type.id
                                            ? 'border-purple-500 bg-purple-50 text-purple-700'
                                            : 'border-gray-200 hover:border-gray-300 text-gray-600'
                                            }`}
                                    >
                                        <Icon className="w-6 h-6" />
                                        <span className="text-sm font-medium">{copy.types[type.id]}</span>
                                    </button>
                                )
                            })}
                        </div>
                    </div>

                    {/* Input Section */}
                    <div className="space-y-6 mb-8">
                        <div>
                            <label htmlFor="qr-value" className="block text-sm font-semibold text-gray-700 mb-2">
                                {copy.contentLabel}
                            </label>
                            <div className="relative">
                                <textarea
                                    id="qr-value"
                                    value={value}
                                    onChange={(e) => setValue(e.target.value)}
                                    rows={3}
                                    className="w-full px-4 py-3 pr-12 rounded-xl border-2 border-gray-200 focus:border-purple-500 focus:ring-2 focus:ring-purple-200 outline-none transition-all resize-none"
                                    placeholder={getPlaceholder()}
                                />
                                <button
                                    onClick={copyToClipboard}
                                    className="absolute right-3 top-3 p-2 hover:bg-gray-100 rounded-lg transition-colors"
                                    title={isSpanish ? 'Copiar texto' : 'Copy text'}
                                >
                                    {copied ? (
                                        <Check className="w-5 h-5 text-green-600" />
                                    ) : (
                                        <Copy className="w-5 h-5 text-gray-400" />
                                    )}
                                </button>
                            </div>
                        </div>

                        <div className="grid md:grid-cols-2 gap-6">
                            <div>
                                <label htmlFor="size" className="block text-sm font-semibold text-gray-700 mb-2">
                                    {copy.sizeLabel}
                                </label>
                                <input
                                    id="size"
                                    type="range"
                                    min="128"
                                    max="512"
                                    step="32"
                                    value={size}
                                    onChange={(e) => setSize(Number(e.target.value))}
                                    className="w-full"
                                />
                                <div className="text-center text-sm text-gray-600 mt-1">{size}px</div>
                            </div>

                            <div>
                                <label htmlFor="error-level" className="block text-sm font-semibold text-gray-700 mb-2">
                                    {copy.errorLabel}
                                </label>
                                <select
                                    id="error-level"
                                    value={errorLevel}
                                    onChange={(e) => setErrorLevel(e.target.value as 'L' | 'M' | 'Q' | 'H')}
                                    className="w-full px-4 py-3 rounded-xl border-2 border-gray-200 focus:border-purple-500 focus:ring-2 focus:ring-purple-200 outline-none transition-all bg-white"
                                >
                                    {Object.entries(copy.errorLevels).map(([key, val]) => (
                                        <option key={key} value={key}>
                                            {val.label}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>
                    </div>

                    {/* Preview Section */}
                    <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl p-8 mb-6">
                        <h3 className="text-lg font-semibold text-gray-900 mb-4 text-center">
                            {copy.previewTitle}
                        </h3>
                        <div ref={qrRef} className="flex justify-center items-center bg-white rounded-xl p-8">
                            {value && (
                                <QRCodeSVG
                                    value={value}
                                    size={size}
                                    level={errorLevel}
                                    includeMargin={true}
                                />
                            )}
                        </div>
                    </div>

                    {/* Download Button */}
                    <button
                        onClick={downloadQR}
                        disabled={!value}
                        className="w-full bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold py-4 px-6 rounded-xl hover:from-purple-700 hover:to-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg hover:shadow-xl flex items-center justify-center gap-2 text-lg"
                    >
                        <Download className="w-5 h-5" />
                        {copy.downloadButton}
                    </button>

                    {/* Info */}
                    <div className="mt-8 p-6 bg-purple-50 rounded-xl border border-purple-100">
                        <h4 className="font-semibold text-purple-900 mb-2">{copy.infoTitle}</h4>
                        <p className="text-sm text-purple-700 mb-3">{copy.infoText}</p>
                        <ul className="text-sm text-purple-700 space-y-1">
                            {Object.entries(copy.errorLevels).map(([key, val]) => (
                                <li key={key}>
                                    <strong>{val.label}:</strong> {val.desc}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>

                {/* Footer */}
                <div className="text-center mt-8 text-gray-500 text-sm">
                    <p>{copy.footer} <span className="font-semibold text-purple-600">Orkiosk</span></p>
                </div>
            </div>
        </div>
    )
}
